### ISSUE TITLE
please make a 0.7.4 release 

### ISSUE THREAD

**Issue by luzpaz** [olivierberten/SwatchBooker#4]
..that includes the fix from https://github.com/olivierberten/SwatchBooker/issues/1

**Comment by luzpaz** [comment]
bump as I'm getting swatchbooker formula in homebrew to work correctly 
ref: https://github.com/Homebrew/homebrew/pull/45682/

**Comment by luzpaz** [comment]
@olivierberten what do you need help with ?

**Comment by olivierberten** [comment]
Well... I guess I didn't feel the need since the current version isn't really working ;-)

Done: https://github.com/olivierberten/SwatchBooker/releases/tag/0.7.4
