### ISSUE TITLE
Swatchbooker description and website 

### ISSUE THREAD

**Issue by luzpaz** [olivierberten/SwatchBooker#5]
Swatchbooker lacks a description and website on it's github page

**Comment by luzpaz** [comment]
@olivierberten ping

**Comment by luzpaz** [comment]
@olivierberten since you merged #8 perhaps you'd like to continue the momentum and fix this issue as welll ?

**Comment by luzpaz** [comment]
Thanks! 
Question: Why not integrate the below description in to the current description?
> SwatchBooker is a free/libre swatches editor and batch convertor for Linux, macOS, and Windows.

**Comment by olivierberten** [comment]
Well... I just copied the description from the launchpad project... And since I haven't really looked a lot into that program in the last 5 years, I have no idea whether it would still work on MacOS and Windows... as I just managed to make it work again on Linux...
